# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
---
name: LDD Automation with PDSEN CI Bot
on:
   push:
     branches:
       - '**'
       - '!master'

env:
  REGRESSION_TEST_PATH: ${{ format('{0}/{1}/', github.workspace, 'test') }}
  # TODO - Have to hard-code this for now since Actions don't yet allow the use of env here.
  LOGS_PATH: ${{ format('{0}/{1}', github.workspace, 'logs') }}
  DEPLOY_PATH: ${{ format('{0}/{1}/{2}/{3}', github.workspace, 'build', 'development', github.sha) }}

jobs:
  get_versions:
    name: Get Applicable PDS4 Versions
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - id: set-matrix
        run: |
          while read -r line; do
              if [[ ! -z "$line" ]]; then
                  versions=$versions'"'$line'"',
              fi
          done < $GITHUB_WORKSPACE/pds4_versions.txt
          versions="[${versions::-1}]"
          echo "{\"pds4_version\":${versions}}"
          
          # Baseline: Set pds4 version to versions from file
          # echo "::set-output name=matrix::{\"pds4_version\": $versions}"
          
          # Example of using development PDS4 Release for v1.16.0.0
          # Update with appropriate version as needed
          echo "::set-output name=matrix::{\"pds4_version\": $versions, \"include\":[{\"pds4_version\":\"1.16.0.0\",\"pds4_development_release\":true}]}"

  build:
    name: 'LDD Build'
    needs: get_versions
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'

    strategy:
      matrix: ${{fromJson(needs.get_versions.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Update submodules for dependencies
        run: |
          git submodule update --init --force --remote

      - name: Generate LDDs
        id: generate
        uses: NASA-PDS/gh-action-pds4-ldd@master
        with:
          data_path: ${{ format('{0}/{1}', env.DEPLOY_PATH, matrix.pds4_version) }}
          pds4_im_version: ${{ matrix.pds4_version }}
          pds4_development_release: ${{ matrix.pds4_development_release }}
          lddtool_development_release: ${{ matrix.lddtool_development_release }}
          test_path: ${{ env.REGRESSION_TEST_PATH }}
          logs_path: ${{ env.LOGS_PATH }}
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Upload LDDs to Github Action Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: v${{matrix.pds4_version}}_LDDs
          path: ${{ env.DEPLOY_PATH }}
        if: ${{ always() }}

      - name: Upload Logs to Github Action Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: v${{matrix.pds4_version}}_execution_logs
          path: ${{ env.LOGS_PATH }}
        if: ${{ always() }}


  upload: # job 2
    name: 'Upload LDDs to Github Repo'
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - uses: actions/download-artifact@v2
        with:
          path: /tmp/artifacts

      - name: Display structure of downloaded files
        run: ls -R /tmp/artifacts

      - name: Clean previous dev/snapshot tags
        run: |
          git fetch --prune --unshallow --tags
          git tag -l | grep 'dev' | xargs -t -I arg sh -c 'git tag -d arg;git push --delete origin arg;'

      - name: Clean out old LDDs
        run: |
          path=$(dirname ${{ env.DEPLOY_PATH }})
          rm -fr $path/*

      - name: Move the LDDs to their new home
        run: |
          mkdir -p ${{ env.DEPLOY_PATH }}
          cp -R /tmp/artifacts/*LDDs/* ${{ env.DEPLOY_PATH }}

      - name: Display structure of downloaded files
        run: ls -R ${{ env.DEPLOY_PATH }}

      - name: If Release Branch, move to release dir
        shell: bash
        run: |
          if [[ "${{github.ref}}" == *"release"* ]]; then
            echo "DEPLOY_PATH=${{github.workspace}}/build/release" >> $GITHUB_ENV
            cp -R ${{ env.DEPLOY_PATH }}/* ${{github.workspace}}/build/release/            
          fi

      - name: Push LDDs to Github
        run: |  
          git config --local user.email "pdsen-ci@jpl.nasa.gov"
          git config --local user.name "PDSEN CI Bot"
          git add -A $(dirname ${{ env.DEPLOY_PATH }})
          git commit -m "Auto-generated LDD by PDSEN CI Bot"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch: ${{ github.ref }}

    needs: build

