# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
---

name: Release and Tag LDD Release

on:
   push:
     branches:
       - 'master'
     paths:
      - 'build/release/**'

env:
  DEPLOY_PATH: ${{ format('{0}/{1}', github.workspace, 'build/release') }}
  # TODO - Have to hard-code this for now since Actions don't yet allow the use of env here.
  LOGS_PATH: ${{ format('{0}/{1}', github.workspace, 'logs') }}

jobs:
  build: # job 1
    name: 'Tag and Release LDD'
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Adding dependencies
        run: |
           sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt1-dev python-libxml2

      - name: Clean previous dev/snapshot tags
        run: |
          git fetch --prune --unshallow --tags
          git tag -l | grep 'dev' | xargs -t -I arg sh -c 'git tag -d arg;git push --delete origin arg;'

      - name: Publish new release
        run: |
           pip install pds-github-util
           ldd-release --ingest_ldd_src_dir ${{github.workspace}}/src --ldd_output_path ${{ env.DEPLOY_PATH }} --token ${{ secrets.GITHUB_TOKEN }}

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      #     branch: ${{ env.GITHUB_REF }}

